name: skillworth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sizer: ^2.0.15
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  material_design_icons_flutter: ^7.0.7296
  intl_phone_number_field: ^0.1.9
  flutter_svg: ^2.0.10+1
  flutter_otp_text_field: ^1.1.1
  image_picker: ^1.0.7
  dotted_border: ^2.1.0
  dropdown_textfield: ^1.0.8
  floating_bottom_navigation_bar: ^1.5.2
  flutter_staggered_grid_view: ^0.7.0
  fl_chart: ^0.66.2
  flutter_multi_select_items: ^0.4.2
  dio: ^5.4.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg_icons/
    - assets/default/
